### PR TITLE
added macos build support

### PR DESCRIPTION
**Pull request by mschmieder**
Patched make config system so it supports building on OSX systems as well.
Patches include:
  * Locating OpenSSL
  * Using the latest Framework
  * patched cxx files to support osx build

### CODE REVIEW

**Comment by katmsft** [comment]
Hi, can you also update the README with how to build on MAC os. This PR supports MAC OS but without a detailed guideline, I do not think it is enough for the new users.

**Comment by seguler** [comment]
pinging @mschmieder  - would you be able to provide guidance in the README file ?

**Comment by mschmieder** [comment]
@seguler 
I added the build instructions. Please check the latest commit.

**Comment by katmsft** [comment]
Hi, thanks for the contribution. In order to support MacOS, I have submitted another PR to resolve this issue. The key difference it to not provide a `FindUUID.cmake` while using `system` library on MacOS that is providing UUID library. Please take a look.

**Comment by vinjiang** [comment]
Feel free to ping us if any further questions.

**Pull request closed without merging**
