### PR TITLE
Build workflow using GitHub actions

### PR DESCRIPTION
**Pull request by damienpontifex**
Swapped PR build validator to use GitHub actions

### CODE REVIEW

**Comment by katmsft** [comment]
It would be best for us to support both Github actions/Azure pipeline.

Thanks for the PR, I'll do some more evaluation.

**Comment by damienpontifex** [comment]
Thanks @katmsft sounds valid. I assumed it might be good to add these as they could add value straight away. Then add the azure pipelines definitions back in once an environment they would run in was provisioned.

Just keep things in the repo while they're being used so as not to confuse things if the azure pipelines definition was there, but wasn't run.

**Comment by damienpontifex** [comment]
@katmsft would you like me to put the azure pipelines files back for this PR? It'd be nice to get PR build checks :)

**Comment by damienpontifex** [comment]
Closing this one as it's now outdated and I see azure pipelines support is integrated now

**Pull request closed without merging**
